CREATE DATABASE USO_INTELIGENTE
USE USO_INTELIGENTE

CREATE TABLE USUARIOS
	(
		ID Int,
		NOMBRE char(20),
		APELLIDO CHAR(20),
		DIRECCION CHAR(100),

		CONSTRAINT USUARIOS_PK PRIMARY KEY (ID)
	);
INSERT INTO USUARIOS(ID, NOMBRE, APELLIDO, DIRECCION) VALUES (1, 'Carlos', 'Carbajal', 'Camino a Quinta Saulo #50');
INSERT INTO USUARIOS(ID, NOMBRE, APELLIDO, DIRECCION) VALUES (2, 'Rafaín', 'Rodríguez', 'Espiritu Santo #8');
INSERT INTO USUARIOS(ID, NOMBRE, APELLIDO, DIRECCION) VALUES (3, 'Javier', 'Rodríguez', 'Calzada de las Orquídeas #4');
INSERT INTO USUARIOS(ID, NOMBRE, APELLIDO, DIRECCION) VALUES (4, 'Juan', 'Gómez', 'Tesorero #20');
INSERT INTO USUARIOS(ID, NOMBRE, APELLIDO, DIRECCION) VALUES (5, 'Allan', 'Sánchez', 'Rincón de la Alegría #34');
INSERT INTO USUARIOS(ID, NOMBRE, APELLIDO, DIRECCION) VALUES (6, 'Pablo', 'Ramos', 'Chiapas #32');
CREATE TABLE CATEGORIAS
	(
		ID int,
		NOMBRE char(20) NOT NULL,


		CONSTRAINT CATEGORIAS_PK PRIMARY KEY (ID)
	);
INSERT INTO CATEGORIAS(ID, NOMBRE) VALUES (1, 'TECNOLOGIA');
INSERT INTO CATEGORIAS(ID, NOMBRE) VALUES (2, 'DESARROLLO URBANO');
INSERT INTO CATEGORIAS(ID, NOMBRE) VALUES (3, 'SOCIEDAD');

CREATE TABLE PROYECTOS
	(
		ID Int,
		NOMBRE char(20) NOT NULL,
		OBJETIVO char(100),
		INTRODUCCION char(100),
		PRESUPUESTO decimal(10,2),
		DIAGNOSTICO char(100),


	 CONSTRAINT PROYECTOS_PK PRIMARY KEY (ID)
	 

	);
CREATE TABLE CATEGORIA_PROYECTO(
    PROYECTO int,
    CATEGORIA int,
    CONSTRAINT PROYECTOS_PK PRIMARY KEY(PROYECTO,CATEGORIA),
    CONSTRAINT PROYECTOS_FK1 FOREIGN KEY (PROYECTO) REFERENCES  PROYECTOS (ID),
    CONSTRAINT PROYECTOS_FK2 FOREIGN KEY (CATEGORIA) REFERENCES  CATEGORIAS (ID)
);
    
INSERT INTO PROYECTOS(ID, NOMBRE, OBJETIVO, INTRODUCCION, PRESUPUESTO, DIAGNOSTICO) VALUES (1, 'TRAYECTO FI', 'Promoción de la ciencia y la tecnología dentro de una comunidad rural', 'Las comunidades rurales necesitan implementar ciencia y tecnología', 83500,'Faltan temas para difundir, comunidades a las cuales generar impacto');
INSERT INTO PROYECTOS(ID, NOMBRE, OBJETIVO, INTRODUCCION, PRESUPUESTO, DIAGNOSTICO) VALUES (2, 'iStudy', 'Difusión de información escolar', 'Facilitar el acceso a la información de las materias, así como las tareas por entregar', 55000.50,'Faltan aterrizar ideas, buscar recursos');
INSERT INTO PROYECTOS(ID, NOMBRE, OBJETIVO, INTRODUCCION, PRESUPUESTO, DIAGNOSTICO) VALUES (3, 'HackMx','Difusión de ciencia y tecnología', 'Buscar soluciones a problemas de hoy en día por medio de tecnología', 46000,'Faltan patrocinadores');
INSERT INTO PROYECTOS(ID, NOMBRE, OBJETIVO, INTRODUCCION, PRESUPUESTO, DIAGNOSTICO) VALUES (4, 'Estamos contigo', 'Reconstrucción de zonas rurales', 'Las comunidades rurales necesitan reconstruirse', 100000,'Faltan materiales para la reconstrucción');
INSERT INTO PROYECTOS(ID, NOMBRE, OBJETIVO, INTRODUCCION, PRESUPUESTO, DIAGNOSTICO) VALUES (5, 'Humano', 'Promoción de los derechos de la comunidad LGBT', 'Fomentar el respeto de la gente que forma parte de la comunidad',20000,'Falta ponentes');

CREATE TABLE ESTADO_PROYECTOS
	(
		FECHA datetime DEFAULT CURRENT_TIMESTAMP,
		PROYECTO Int,
		ESTADO char(3),
		CONSTRAINT ESTADO_PROYECTOS_PK PRIMARY KEY (FECHA,PROYECTO,ESTADO),
		CONSTRAINT ESTADO_PROYECTOS_FK FOREIGN KEY (PROYECTO) REFERENCES PROYECTOS (ID)
	);
INSERT INTO ESTADO_PROYECTOS(PROYECTO,ESTADO) VALUES (1,'EPC');
INSERT INTO ESTADO_PROYECTOS(PROYECTO,ESTADO) VALUES (2,'EPC');
INSERT INTO ESTADO_PROYECTOS(PROYECTO,ESTADO) VALUES (3,'CAN');
INSERT INTO ESTADO_PROYECTOS(PROYECTO,ESTADO) VALUES (4,'EPC');
INSERT INTO ESTADO_PROYECTOS(PROYECTO,ESTADO) VALUES (5,'COM');

CREATE TABLE USUARIO_PROYECTOS
	(
		USUARIO Int,
		PROYECTO Int,

		CONSTRAINT USUARIO_PROYECTOS_PK PRIMARY KEY (USUARIO,PROYECTO),
		CONSTRAINT USUARIO_PROYECTOS_FK1 FOREIGN KEY (USUARIO) REFERENCES  USUARIOS (ID),
		CONSTRAINT USUARIO_PROYECTOS_FK2 FOREIGN KEY (PROYECTO) REFERENCES PROYECTOS (ID)
	);

CREATE TABLE NOTAS_PROYECTOS
	(
		PROYECTO Int,
		USUARIO Int,
		FECHA datetime DEFAULT CURRENT_TIMESTAMP,
		NOTA char(255),


	 CONSTRAINT NOTAS_PROYECTOS_PK PRIMARY KEY (PROYECTO, USUARIO, FECHA),
	 CONSTRAINT NOTAS_PROYECTOS_FK1 FOREIGN KEY (PROYECTO) REFERENCES  PROYECTOS (ID),
	 CONSTRAINT NOTAS_PROYECTOS_FK2 FOREIGN KEY (USUARIO) REFERENCES  USUARIOS (ID)
	);
