CREATE VIEW UltimoMes AS(
  Select PROYECTOS.ID, PROYECTOS.NOMBRE, PROYECTOS.PRESUPUESTO, ESTADO_PROYECTOS.ESTADO
  FROM PROYECTOS INNER JOIN ESTADO_PROYECTOS
  ON PROYECTOS.ID = ESTADO_PROYECTOS.PROYECTO
  INNER JOIN NOTAS_PROYECTOS
  ON NOTAS_PROYECTOS.PROYECTO = PROYECTOS.ID
  WHERE ESTADO_PROYECTOS.FECHA > DATE_ADD(NOW(), INTERVAL -1 MONTH)
  OR NOTAS_PROYECTOS.FECHA > DATE_ADD(NOW(), INTERVAL -1 MONTH)
);
CREATE VIEW ResumenProyectos AS(
  SELECT PROYECTOS.ID AS ID, PROYECTOS.NOMBRE AS PROYECTO ,ESTADO_PROYECTOS.ESTADO AS ESTADO, PROYECTOS.PRESUPUESTO AS FONDOS
  FROM PROYECTOS INNER JOIN ESTADO_PROYECTOS
  ON PROYECTOS.ID = ESTADO_PROYECTOS.PROYECTO
  
);
